### ISSUE TITLE
Apps like Whatsapp, Facebook, Instagram, Signal are not working

### ISSUE THREAD

**Issue by AmanArora1987** [Monster-GM/NewBlackbox#1]
Apps like whatsapp, facebook, instagram, signal are getting closed unexpedctedly

**Comment by AmanArora1987** [comment]
Like for WhatsApp found below in logs
`
ava.lang.RuntimeException: Permission com.whatsapp.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION is required by your application to receive broadcasts, please add it to your manifest
                                                                                                    	at X.001.A0m(:2)
                                                                                                    	at X.0YK.A0A(:54)
                                                                                                    	at X.0R6.A00(:9)
                                                                                                    	at X.0YK.A07(:51)
                                                                                                    	at X.0YK.A06(:6)
                                                                                                    	at X.0vB.A11(:5)
                                                                                                    	at X.0x1.handleMessage(:422)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:238)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7824)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
`
