### ISSUE TITLE
安卓13 14 微信打不开

### ISSUE THREAD

**Issue by wordgege** [Monster-GM/NewBlackbox#3]
微信打不开,抖音 快手闪退打不开
oppo
vivo
一加
pixel
都是这样 unable make application
这个新的blackbox还在维护吗

**Comment by dujianchi** [comment]
淘宝也打不开
日志如下：
```
---------------------------- PROCESS STARTED (516) for package top.niunaijun.blackbox ----------------------------
2023-10-27 10:08:07.034   516-516   Compatibil...geReporter top.niunaijun.blackbox               D  Compat change id reported: 171979766; UID 10386; state: ENABLED
2023-10-27 10:08:07.035  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14534   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.blackbox.view.main.WelcomeActivity} }
2023-10-27 10:08:07.055  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14534   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.blackbox.view.main.WelcomeActivity} }
2023-10-27 10:08:07.086   516-516   Perf                    top.niunaijun.blackbox               I  Connecting to perf service.
2023-10-27 10:08:07.092   516-516   GraphicsEnvironment     top.niunaijun.blackbox               V  ANGLE Developer option for 'top.niunaijun.blackbox' set to: 'default'
2023-10-27 10:08:07.092   516-516   GraphicsEnvironment     top.niunaijun.blackbox               V  ANGLE GameManagerService for top.niunaijun.blackbox: false
2023-10-27 10:08:07.092   516-516   GraphicsEnvironment     top.niunaijun.blackbox               V  Updatable production driver is not supported on the device.
2023-10-27 10:08:07.098   516-516   ForceDarkHelperStubImpl top.niunaijun.blackbox               I  initialize for top.niunaijun.blackbox , ForceDarkOrigin
2023-10-27 10:08:07.100   516-516   jun.blackbox:p0         top.niunaijun.blackbox               D  JNI_OnLoad success
2023-10-27 10:08:07.100   516-516   MiuiForceDarkConfig     top.niunaijun.blackbox               I  setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
2023-10-27 10:08:07.099   516-516   jun.blackbox:p0         top.niunaijun.blackbox               W  type=1400 audit(0.0:271069): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=388 scontext=u:r:untrusted_app:s0:c130,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.orpheusdroid.screenrecorder
2023-10-27 10:08:07.102   516-516   libc                    top.niunaijun.blackbox               W  Access denied finding property "ro.vendor.df.effect.conflict"
2023-10-27 10:08:07.105   516-516   NetworkSecurityConfig   top.niunaijun.blackbox               D  Using Network Security Config from resource network_security_config debugBuild: true
2023-10-27 10:08:07.108   516-516   NetworkSecurityConfig   top.niunaijun.blackbox               D  Using Network Security Config from resource network_security_config debugBuild: true
2023-10-27 10:08:07.240   516-516   Reflector               top.niunaijun.blackbox               E  meizu.security.IFlymePermissionService
2023-10-27 10:08:07.249   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IPackageManagerProxy@a12665d
2023-10-27 10:08:07.260   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ITelephonyManagerProxy@dba47ff
2023-10-27 10:08:07.273   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IUserManagerProxy@1b532a
2023-10-27 10:08:07.278   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IVibratorServiceProxy@6eacc91
2023-10-27 10:08:07.280   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IActivityClientProxy@c0e4664
2023-10-27 10:08:07.285   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IAlarmManagerProxy@7a15c93
2023-10-27 10:08:07.286   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IPersistentDataBlockServiceProxy@fdd8fce
2023-10-27 10:08:07.287   516-516   HookManager             top.niunaijun.blackbox               D  hook error: top.niunaijun.bcore.fake.service.IPersistentDataBlockServiceProxy@fdd8fce Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
2023-10-27 10:08:07.287   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IAppWidgetManagerProxy@a7b2eef
2023-10-27 10:08:07.291   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ISystemUpdateProxy@146dada
2023-10-27 10:08:07.294   516-516   HookManager             top.niunaijun.blackbox               D  hook error: top.niunaijun.bcore.fake.service.ISystemUpdateProxy@146dada Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
2023-10-27 10:08:07.294   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IMediaRouterServiceProxy@75cb0b
2023-10-27 10:08:07.298   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ILocationManagerProxy@fc7caa6
2023-10-27 10:08:07.305   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IFingerprintManagerProxy@b26573d
2023-10-27 10:08:07.307   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.context.ContentServiceProxy@9f9a200
2023-10-27 10:08:07.309   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IDevicePolicyManagerProxy@17bb1df
2023-10-27 10:08:07.319   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IAppOpsManagerProxy@3fbae8a
2023-10-27 10:08:07.322   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IStorageManagerProxy@585e771
2023-10-27 10:08:07.325   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.INetworkManagementServiceProxy@6d4c6c4
2023-10-27 10:08:07.328   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IJobServiceProxy@b20a073
2023-10-27 10:08:07.330   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IMediaSessionManagerProxy@3110d2e
2023-10-27 10:08:07.334   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ISubProxy@7364165
2023-10-27 10:08:07.338   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.delegate.AppInstrumentation@6b79048
2023-10-27 10:08:07.338   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IAutofillManagerProxy@9ce8ee1
2023-10-27 10:08:07.341   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IConnectivityManagerProxy@ad968f4
2023-10-27 10:08:07.345   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ILauncherAppsProxy@af28c63
2023-10-27 10:08:07.347   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IContextHubServiceProxy@ff11dde
2023-10-27 10:08:07.348   516-516   HookManager             top.niunaijun.blackbox               D  hook error: top.niunaijun.bcore.fake.service.IContextHubServiceProxy@ff11dde Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
2023-10-27 10:08:07.349   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ITelephonyRegistryProxy@8778bbf
2023-10-27 10:08:07.354   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.BuildProxy@a6d39ea
2023-10-27 10:08:07.354   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IPermissionManagerProxy@407f251
2023-10-27 10:08:07.356   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IDisplayManagerProxy@822f724
2023-10-27 10:08:07.358   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IPowerManagerProxy@1cf5453
2023-10-27 10:08:07.361   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IBluetoothManagerProxy@d0eba8e
2023-10-27 10:08:07.364   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IShortcutManagerProxy@ac45645
2023-10-27 10:08:07.366   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IGraphicsStatsProxy@2e0d2a8
2023-10-27 10:08:07.367   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IActivityTaskManagerProxy@fd911c1
2023-10-27 10:08:07.373   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IWifiManagerProxy@6c319f2
2023-10-27 10:08:07.379   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IFlymePermissionServiceProxy@12d37f9
2023-10-27 10:08:07.379   516-516   Reflector               top.niunaijun.blackbox               E  meizu.security.IFlymePermissionService$Stub
2023-10-27 10:08:07.380   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IActivityManagerProxy@ae4e33e
2023-10-27 10:08:07.389   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.libcore.OsProxy@7005ab5
2023-10-27 10:08:07.394   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.HCallbackProxy@5181c16
2023-10-27 10:08:07.395   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IStorageStatsManagerProxy@2d6d997
2023-10-27 10:08:07.398   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IVpnManagerProxy@f71e3a2
2023-10-27 10:08:07.401   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IAccountManagerProxy@bcf1169
2023-10-27 10:08:07.410   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IPhoneSubInfoProxy@179931c
2023-10-27 10:08:07.411   516-516   HookManager             top.niunaijun.blackbox               D  hook error: top.niunaijun.bcore.fake.service.IPhoneSubInfoProxy@179931c Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
2023-10-27 10:08:07.412   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IWindowManagerProxy@f3e5b25
2023-10-27 10:08:07.417   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IRoleManagerProxy@a1ac508
2023-10-27 10:08:07.419   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.INotificationManagerProxy@98b5687
2023-10-27 10:08:07.424   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.context.RestrictionsManagerProxy@9fe7952
2023-10-27 10:08:07.426   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IWifiScannerProxy@61226d9
2023-10-27 10:08:07.428   516-516   HookManager             top.niunaijun.blackbox               D  hook error: top.niunaijun.bcore.fake.service.IWifiScannerProxy@61226d9 Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
2023-10-27 10:08:07.429   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IAccessibilityManagerProxy@266d89e
2023-10-27 10:08:07.430   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.ISearchManagerProxy@5f55795
2023-10-27 10:08:07.432   516-516   HookManager             top.niunaijun.blackbox               D  hook: top.niunaijun.bcore.fake.service.IDeviceIdentifiersPolicyProxy@d8d8038
2023-10-27 10:08:07.440   516-516   IActivityManagerProxy   top.niunaijun.blackbox               D  Innovate getContentProvider: settings
2023-10-27 10:08:07.446 30115-30246 BProcessManager         top.niunaijun.blackbox               D  init pid = 516
2023-10-27 10:08:07.449   516-516   IActivityManagerProxy   top.niunaijun.blackbox               D  Innovate getContentProvider: top.niunaijun.blackbox.blackbox.SystemCallProvider
2023-10-27 10:08:07.449   516-516   IActivityManagerProxy   top.niunaijun.blackbox               D  ProxyManifest.isProxy: top.niunaijun.blackbox.blackbox.SystemCallProvider
2023-10-27 10:08:07.453 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=88]
2023-10-27 10:08:07.454   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: activity_manager, android.os.BinderProxy@420566f
2023-10-27 10:08:07.455 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=76]
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  java.lang.NoClassDefFoundError: Failed resolution of: Lblack/com/android/internal/R$styleable;
2023-10-27 10:08:07.456   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: job_manager, android.os.BinderProxy@4f4cf7c
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  	at top.niunaijun.bcore.core.system.am.ActivityStack.getStartStubActivityIntentInner(ActivityStack.java:311)
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  	at top.niunaijun.bcore.core.system.am.ActivityStack.startActivityProcess(ActivityStack.java:255)
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  	at top.niunaijun.bcore.core.system.am.ActivityStack.startActivityInNewTaskLocked(ActivityStack.java:260)
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  	at top.niunaijun.bcore.core.system.am.ActivityStack.startActivityLocked(ActivityStack.java:140)
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  	at top.niunaijun.bcore.core.system.am.BActivityManagerService.startActivity(BActivityManagerService.java:335)
2023-10-27 10:08:07.456 30115-30246 System.err              top.niunaijun.blackbox               W  	at top.niunaijun.bcore.core.system.am.IBActivityManagerService$Stub.onTransact(IBActivityManagerService.java:200)
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  	at android.os.Binder.execTransactInternal(Binder.java:1285)
2023-10-27 10:08:07.457 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=84]
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  	at android.os.Binder.execTransact(Binder.java:1249)
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  Caused by: java.lang.ClassNotFoundException: Didn't find class "black.com.android.internal.R$styleable" on path: DexPathList[[zip file "/data/app/~~iCK7LLlx1PaLmmddkoTwCg==/top.niunaijun.blackbox-F39I3X-AQA_Nulxbeg4XNw==/base.apk"],nativeLibraryDirectories=[/data/app/~~iCK7LLlx1PaLmmddkoTwCg==/top.niunaijun.blackbox-F39I3X-AQA_Nulxbeg4XNw==/lib/arm64, /data/app/~~iCK7LLlx1PaLmmddkoTwCg==/top.niunaijun.blackbox-F39I3X-AQA_Nulxbeg4XNw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-10-27 10:08:07.457 30115-30246 System.err              top.niunaijun.blackbox               W  	... 8 more
2023-10-27 10:08:07.457   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: package_manager, android.os.BinderProxy@95c5005
2023-10-27 10:08:07.458 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=84]
2023-10-27 10:08:07.459   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: storage_manager, android.os.BinderProxy@58dc85a
2023-10-27 10:08:07.460 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=80]
2023-10-27 10:08:07.460   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: user_manager, android.os.BinderProxy@5ea8b
2023-10-27 10:08:07.464 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=84]
2023-10-27 10:08:07.465   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: xposed_manager, android.os.BinderProxy@27d6768
2023-10-27 10:08:07.466  1323-1323  vendor.qti...al-service ven...qti.hardware.perf-hal-service  E  ExtendedPerfBoost: extended_perfboost_verification() 738: Ok, set boost params. hintid=4226 hinttype=1 prio=2, clientpid=2424 packagename=top.niunaijun.blackbox params=boost:1 cpu0:1804800 cpu4:2496000 cpu7:2592000 cpumask:ff
2023-10-27 10:08:07.466 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=84]
2023-10-27 10:08:07.467   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: account_manager, android.os.BinderProxy@756e781
2023-10-27 10:08:07.469 28339-513   BpBinder                top.niunaijun.blackbox               W  PerfMonitor binderTransact :  time=518ms interface=top.niunaijun.bcore.core.system.am.IBActivityManagerService code=3
2023-10-27 10:08:07.470 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=88]
2023-10-27 10:08:07.471   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: location_manager, android.os.BinderProxy@9501026
2023-10-27 10:08:07.471  1323-1323  vendor.qti...al-service ven...qti.hardware.perf-hal-service  E  ExtendedPerfBoost: extended_perfboost_verification() 738: Ok, set boost params. hintid=4226 hinttype=1 prio=2, clientpid=2424 packagename=top.niunaijun.blackbox params=boost:1 cpu0:1804800 cpu4:2496000 cpu7:2592000 cpumask:ff
2023-10-27 10:08:07.473 30115-30141 SystemCallProvider      top.niunaijun.blackbox               D  call: VM, Bundle[mParcelledData.dataSize=96]
2023-10-27 10:08:07.474   516-516   BlackBoxCore            top.niunaijun.blackbox               D  getService: notification_manager, android.os.BinderProxy@f66a467
2023-10-27 10:08:07.480   516-576   AppScoutStateMachine    top.niunaijun.blackbox               D  516-ScoutStateMachinecreated
2023-10-27 10:08:07.484 28339-28339 DecorView[]             top.niunaijun.blackbox               D  onWindowFocusChanged hasWindowFocus false
2023-10-27 10:08:07.490   516-516   NativeCore              top.niunaijun.blackbox               D  NativeCore init.
2023-10-27 10:08:07.492  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14536   userId=0   baseIntent=Intent { act=null flag=403177472 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.bcore.proxy.ProxyActivity$P0} }
2023-10-27 10:08:07.492  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14534   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.blackbox.view.main.WelcomeActivity} }
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：canonicalize0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：getLastModifiedTime0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：setPermission0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：createFileExclusively0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：list0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：createDirectory0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：setLastModifiedTime0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：setReadOnly0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/io/UnixFileSystem, method：getSpace0 success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：access success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：chmod success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：chown success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：execv success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：execve success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：getxattr success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：lchown success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：link success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：listxattr success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：lstat success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：mkdir success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：mkfifo success!
2023-10-27 10:08:07.508   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：open success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：readlink success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：realpath success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：remove success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：removexattr success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：rename success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：stat success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：statvfs success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：symlink success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：libcore/io/Linux, method：unlink success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/lang/VMClassLoader, method：findLoadedClass success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：java/lang/Runtime, method：nativeLoad success!
2023-10-27 10:08:07.509   516-516   NativeCore              top.niunaijun.blackbox               D  Register class：android/os/Binder, method：getCallingUid success!
2023-10-27 10:08:07.509   516-516   BlackBoxLoader          top.niunaijun.blackbox               D  beforeCreateApplication: pkg com.taobao.taobao, processName com.taobao.taobao, userID:0
2023-10-27 10:08:07.510   516-516   ApplicationLoaders      top.niunaijun.blackbox               D  Returning zygote-cached class loader: /system/framework/android.test.base.jar
2023-10-27 10:08:07.512   516-516   ziparchive              top.niunaijun.blackbox               W  Unable to open '/data/app/~~UhPswR1JXAssIbZ-5xHyrw==/com.taobao.taobao-prR3apQiOPhfHZNO-YUJqA==/base.dm': No such file or directory
2023-10-27 10:08:07.512   516-516   ziparchive              top.niunaijun.blackbox               W  Unable to open '/data/app/~~UhPswR1JXAssIbZ-5xHyrw==/com.taobao.taobao-prR3apQiOPhfHZNO-YUJqA==/base.dm': No such file or directory
2023-10-27 10:08:07.579  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14536   userId=0   baseIntent=Intent { act=null flag=403177472 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.bcore.proxy.ProxyActivity$P0} }
2023-10-27 10:08:07.579  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14534   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.blackbox.view.main.WelcomeActivity} }
2023-10-27 10:08:07.582  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14536   userId=0   baseIntent=Intent { act=null flag=403177472 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.bcore.proxy.ProxyActivity$P0} }
2023-10-27 10:08:07.582  4343-5470  ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=14534   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{top.niunaijun.blackbox/top.niunaijun.blackbox.view.main.WelcomeActivity} }
2023-10-27 10:08:08.152   516-631   TCrash                  com.taobao.taobao                    E  BlackDevice:->/data/user/0/top.niunaijun.blackbox/blackbox/data/user/0/com.taobao.taobao/cache
2023-10-27 10:08:08.168  2424-5912  DatabaseUtils           system_server                        E  Writing exception to parcel
                                                                                                    java.lang.SecurityException: top.niunaijun.blackbox was not granted  this permission: android.permission.WRITE_SETTINGS.
                                                                                                    	at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:18510)
                                                                                                    	at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:18398)
                                                                                                    	at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:1918)
                                                                                                    	at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:1884)
                                                                                                    	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:475)
                                                                                                    	at android.content.ContentProvider.call(ContentProvider.java:2533)
                                                                                                    	at android.content.ContentProvider$Transport.call(ContentProvider.java:530)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1285)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1249)
2023-10-27 10:08:08.731   516-769   RemoteSo                com.taobao.taobao                    E  StorageUtils, ensureUniqueRuntimeDir complete, dir = /data/user/0/top.niunaijun.blackbox/blackbox/data/user/0/com.taobao.taobao/app_swallows/runtime_dir/598649363/nativeLib
2023-10-27 10:08:08.732   516-769   RemoteSo                com.taobao.taobao                    E  SWSoLoaderCore, installDir finished, dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~UhPswR1JXAssIbZ-5xHyrw==/com.taobao.taobao-prR3apQiOPhfHZNO-YUJqA==/base.apk"],nativeLibraryDirectories=[/data/user/0/top.niunaijun.blackbox/blackbox/data/user/0/com.taobao.taobao/app_swallows/runtime_dir/598649363/nativeLib, /data/app/~~UhPswR1JXAssIbZ-5xHyrw==/com.taobao.taobao-prR3apQiOPhfHZNO-YUJqA==/lib/arm64, /data/app/~~UhPswR1JXAssIbZ-5xHyrw==/com.taobao.taobao-prR3apQiOPhfHZNO-YUJqA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
2023-10-27 10:08:08.732   516-769   RemoteSo                com.taobao.taobao                    E  SWSoLoaderCore, ready ensure symlink = /data/user/0/top.niunaijun.blackbox/blackbox/data/user/0/com.taobao.taobao/app_swallows/runtime_dir/598649363/nativeLib/libpexwebp.so  ->  /data/app/~~UhPswR1JXAssIbZ-5xHyrw==/com.taobao.taobao-prR3apQiOPhfHZNO-YUJqA==/lib/arm64/libpexwebp.so
---------------------------- PROCESS ENDED (516) for package top.niunaijun.blackbox ----------------------------

```

**Comment by shishixiu** [comment]
微信闪退……显示要修复啥的

**Comment by Monster-GM** [comment]
修復了
