### ISSUE TITLE
运行unity游戏突然闪退

### ISSUE THREAD

**Issue by 111304037** [Monster-GM/NewBlackbox#7]
大大，有空能看下这个吗，下面是log

11-24 10:05:41.953 27516 28001 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-24 10:05:41.953 27516 28001 E CRASH   : Version '2020.3.37f1c1 (9f30be21c416)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
11-24 10:05:41.953 27516 28001 E CRASH   : Build fingerprint: 'OPPO/PGJM10/OP5297:12/SP1A.210812.016/S.202204250149:user/release-keys'
11-24 10:05:41.953 27516 28001 E CRASH   : Revision: '0'
11-24 10:05:41.953 27516 28001 E CRASH   : ABI: 'arm64'
11-24 10:05:41.953 27516 28001 E CRASH   : Timestamp: 2023-11-24 10:05:41+0800
11-24 10:05:41.953 27516 28001 E CRASH   : pid: 27516, tid: 28001, name: Thread-58  >>> 包名 <<<
11-24 10:05:41.953 27516 28001 E CRASH   : uid: 10299
11-24 10:05:41.953 27516 28001 E CRASH   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-24 10:05:41.953 27516 28001 E CRASH   :     x0  0000000000000000  x1  0000000000006d61  x2  0000000000000006  x3  000000701ba025a0
11-24 10:05:41.953 27516 28001 E CRASH   :     x4  5151441f43445342  x5  5151441f43445342  x6  5151441f43445342  x7  7f7f7f7f7f7f7f7f
11-24 10:05:41.953 27516 28001 E CRASH   :     x8  00000000000000f0  x9  000000731b42b2c0  x10 ffffff00fffffbdf  x11 0000000000000001
11-24 10:05:41.953 27516 28001 E CRASH   :     x12 000000701ba01310  x13 00000000000000c7  x14 000000701ba013c0  x15 000000c965a9e4c7
11-24 10:05:41.953 27516 28001 E CRASH   :     x16 000000731b4efbb0  x17 000000731b4cb450  x18 0000000000000002  x19 00000000000000ac
11-24 10:05:41.953 27516 28001 E CRASH   :     x20 0000000000006b7c  x21 00000000000000b2  x22 0000000000006d61  x23 00000000ffffffff
11-24 10:05:41.953 27516 28001 E CRASH   :     x24 000000701ba027c0  x25 000000701ba04000  x26 0000007286217000  x27 000000701ba02b10
11-24 10:05:41.953 27516 28001 E CRASH   :     x28 000000701ba02fa8  x29 000000701ba02620
11-24 10:05:41.953 27516 28001 E CRASH   :     sp  000000701ba02580  lr  000000731b47cb6c  pc  000000731b47cb9c
11-24 10:05:41.953 27516 28001 E CRASH   : backtrace:
11-24 10:05:41.953 27516 28001 E CRASH   :       #00 pc 0000000000078b9c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId: f24f65acf653c409ca4332aced817a71)
11-24 10:05:41.953 27516 28001 E CRASH   :       #01 pc 00000000006d7bbc  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+668) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #02 pc 000000000001595c  /apex/com.android.art/lib64/libbase.so (BuildId: 225cc3496ad7ce1867ed9bd3357de134)
11-24 10:05:41.953 27516 28001 E CRASH   :       #03 pc 0000000000014f8c  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+364) (BuildId: 225cc3496ad7ce1867ed9bd3357de134)
11-24 10:05:41.953 27516 28001 E CRASH   :       #04 pc 00000000003d6f4c  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2440) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #05 pc 000000000058d6f8  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+108) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #06 pc 0000000000588790  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+140) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #07 pc 000000000058dac8  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckMethodAndSig(art::ScopedObjectAccess&, _jobject*, _jclass*, _jmethodID*, art::Primitive::Type, art::InvokeType)+260) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #08 pc 000000000057609c  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+468) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #09 pc 000000000057855c  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallIntMethod(_JNIEnv*, _jobject*, _jmethodID*, ...) (.llvm.13036589948386079409)+148) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:41.953 27516 28001 E CRASH   :       #10 pc 00000000000039fc  <anonymous:000000702245f000>
11-24 10:05:42.252 27516 27589 E CRASH   : other thread is trapped; signum = 6
--------- beginning of crash
11-24 10:05:42.255 27516 27589 E AndroidRuntime: FATAL EXCEPTION: UnityMain
11-24 10:05:42.255 27516 27589 E AndroidRuntime: Process: 包名, PID: 27516
11-24 10:05:42.255 27516 27589 E AndroidRuntime: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-24 10:05:42.255 27516 27589 E AndroidRuntime: Version '2020.3.37f1c1 (9f30be21c416)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
11-24 10:05:42.255 27516 27589 E AndroidRuntime: Build fingerprint: 'OPPO/PGJM10/OP5297:12/SP1A.210812.016/S.202204250149:user/release-keys'
11-24 10:05:42.255 27516 27589 E AndroidRuntime: Revision: '0'
11-24 10:05:42.255 27516 27589 E AndroidRuntime: ABI: 'arm64'
11-24 10:05:42.255 27516 27589 E AndroidRuntime: Timestamp: 2023-11-24 10:05:41+0800
11-24 10:05:42.255 27516 27589 E AndroidRuntime: pid: 27516, tid: 28001, name: Thread-58  >>> 包名 <<<
11-24 10:05:42.255 27516 27589 E AndroidRuntime: uid: 10299
11-24 10:05:42.255 27516 27589 E AndroidRuntime: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x0  0000000000000000  x1  0000000000006d61  x2  0000000000000006  x3  000000701ba025a0
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x4  5151441f43445342  x5  5151441f43445342  x6  5151441f43445342  x7  7f7f7f7f7f7f7f7f
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x8  00000000000000f0  x9  000000731b42b2c0  x10 ffffff00fffffbdf  x11 0000000000000001
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x12 000000701ba01310  x13 00000000000000c7  x14 000000701ba013c0  x15 000000c965a9e4c7
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x16 000000731b4efbb0  x17 000000731b4cb450  x18 0000000000000002  x19 00000000000000ac
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x20 0000000000006b7c  x21 00000000000000b2  x22 0000000000006d61  x23 00000000ffffffff
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x24 000000701ba027c0  x25 000000701ba04000  x26 0000007286217000  x27 000000701ba02b10
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     x28 000000701ba02fa8  x29 000000701ba02620
11-24 10:05:42.255 27516 27589 E AndroidRuntime:     sp  000000701ba02580  lr  000000731b47cb6c  pc  000000731b47cb9c
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 
11-24 10:05:42.255 27516 27589 E AndroidRuntime: backtrace:
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #00 pc 0000000000078b9c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId: f24f65acf653c409ca4332aced817a71)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #01 pc 00000000006d7bbc  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+668) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #02 pc 000000000001595c  /apex/com.android.art/lib64/libbase.so (BuildId: 225cc3496ad7ce1867ed9bd3357de134)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #03 pc 0000000000014f8c  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+364) (BuildId: 225cc3496ad7ce1867ed9bd3357de134)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #04 pc 00000000003d6f4c  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2440) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #05 pc 000000000058d6f8  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+108) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #06 pc 0000000000588790  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+140) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #07 pc 000000000058dac8  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckMethodAndSig(art::ScopedObjectAccess&, _jobject*, _jclass*, _jmethodID*, art::Primitive::Type, art::InvokeType)+260) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #08 pc 000000000057609c  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+468) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #09 pc 000000000057855c  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallIntMethod(_JNIEnv*, _jobject*, _jmethodID*, ...) (.llvm.13036589948386079409)+148) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
11-24 10:05:42.255 27516 27589 E AndroidRuntime:       #10 pc 00000000000039fc  <anonymous:000000702245f000>
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libc.abort(abort:180)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::Runtime::Abort(char const*)(Abort:668)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libbase.0x1595c(Native Method)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libbase.android::base::LogMessage::~LogMessage()(~LogMessage:364)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::JavaVMExt::JniAbort(char const*, char const*)(JniAbort:2440)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)(JniAbortV:108)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)(:140)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::(anonymous namespace)::ScopedCheck::CheckMethodAndSig(art::ScopedObjectAccess&, _jobject*, _jclass*, _jmethodID*, art::Primitive::Type, art::InvokeType)(:260)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)(:468)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at libart.art::(anonymous namespace)::CheckJNI::CallIntMethod(_JNIEnv*, _jobject*, _jmethodID*, ...) (.llvm.13036589948386079409)(:148)
11-24 10:05:42.255 27516 27589 E AndroidRuntime: 	at Unknown.0x70224629fc(Unknown Source:0)
11-24 10:05:42.475 27516 27589 E Parcel  : Reading a NULL string not supported here.
11-24 10:05:42.541 27516 27589 I Process : Sending signal. PID: 27516 SIG: 9

**Comment by Monster-GM** [comment]
好的，我有时间看看
