### ISSUE TITLE
今日头条极速版闪退

### ISSUE THREAD

**Issue by 111304037** [Monster-GM/NewBlackbox#9]
**Describe the bug**
今日头条极速版闪退
以下是报错log

java.lang.IllegalArgumentException: field android.app.LoadedApk$ServiceDispatcher.mConnection has type android.content.ServiceConnection, got top.niunaijun.bcore.fake.delegate.ServiceConnectionDelegate
at java.lang.reflect.Field.set(Native Method)
at black.Reflector$FieldWrapper.set(Reflector.java:323)
at top.niunaijun.bcore.fake.service.IActivityManagerProxy$BindService.hook(IActivityManagerProxy.java:275)
at top.niunaijun.bcore.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:117)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy23.bindIsolatedService(Unknown Source)
at java.lang.reflect.Method.invoke(Native Method)
at com.bytedance.bdauditsdkbase.internal.proxy.chain.ProcessHandlerChain.a(SourceFile:33882194)
at X.1ss.process(SourceFile:17104999)
at com.bytedance.bdauditsdkbase.internal.proxy.chain.ProcessHandlerChain.a(SourceFile:33882187)
at X.1sY.invoke(SourceFile:50593841)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy48.bindIsolatedService(Unknown Source)
at java.lang.reflect.Method.invoke(Native Method)
at X.1p0.invoke(SourceFile:50790655)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy48.bindIsolatedService(Unknown Source)
at java.lang.reflect.Method.invoke(Native Method)
at X.1eV.invoke(SourceFile:50724969)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy68.bindIsolatedService(Unknown Source)
at java.lang.reflect.Method.invoke(Native Method)
at X.9bk.a(SourceFile:634)
at com.ss.alive.monitor.a.a.a.a.invoke(SourceFile:50462724)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy48.bindIsolatedService(Unknown Source)
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1863)
at android.app.ContextImpl.bindService(ContextImpl.java:1778)
at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
at X.9ii.a(Unknown Source:72)
at X.9ii.c(SourceFile:17104988)
at X.9ii.a(SourceFile:111)
at X.9ii.a(SourceFile:34013278)
at X.9ii.a(SourceFile:435)
at com.bytedance.common.wschannel.WsChannelSdk.doRealRegisterOrParametersChangedMethod(SourceFile:17039406)
at com.bytedance.common.wschannel.WsChannelSdk.registerChannel(SourceFile:17039401)
at com.bytedance.common.wschannel.WsChannelSdk.registerToutianChannel(SourceFile:33685511)
at X.74F.a(SourceFile:393341)
at com.ss.android.article.lite.ArticleApplication.initWsChannel(SourceFile:262174)
at X.6cQ.run(SourceFile:196635)
at X.4fi.run(SourceFile:196633)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
at X.3fd.run(SourceFile:262191)

**Comment by 111304037** [comment]
算了，放弃了，玩一段时间，感觉问题还是挺多的 -。-
